[workspace]
resolver = "2"
members = [
    "fvm",
    "sdk",
    "shared",
    "testing/conformance",
    "testing/integration",
    "ipld/*",
]

[profile.actor]
inherits = "release"
panic = "abort"
overflow-checks = true
lto = true
opt-level = "z"
#strip = true

# When testing, compile dependencies with optimizations enabled. Otherwise, wasmtime is kind of
# slow.
[profile.test.package."*"]
opt-level = 3
